### PR TITLE
Scroll to current date when opened

### PR DESCRIPTION
**Pull request by michaeljacobdavis**
Similar to #7 but without the timeout. Personally, I like it to reset on re-opening but I might use it differently than others so I'm open to adding a timeout.

### CODE REVIEW

**Comment by bmathews** [comment]
Thanks!

**Comment by bmathews** [comment]
Great work on these few changes, by the way. Really helpful. I still need to do a bit of work on the data syncing/performance/pagination of events. Don't hold me liable if you miss a meeting. ;)

**Comment by bmathews** [comment]
@michaeljacobdavis I gave you contribution access, but let's still stick with the PR/Review model.

**Comment by michaeljacobdavis** [comment]
@bmathews Thanks man and thanks for your work on this.

No problem. Ya I noticed a couple things (meetings in a few months don't show) but I mostly just care about the current week. If you want to open issues, I can grab them.

**Pull request merged**
